const shipments = [
  {
    id: "S/080124/00",
    commodity: "Cotton",
    destination: "Colombo",
    type: "Sea",
    grossWeight: "1000kg",
    status: "Processing",
  },
  {
    id: "S/080124/01",
    commodity: "Rubber bands",
    destination: "London",
    type: "Air",
    grossWeight: "1,500 KG",
    status: "Processing",
  },
  {
    id: "S/080124/02",
    commodity: "Gloves",
    destination: "Tokyo",
    type: "Air",
    grossWeight: "500kg",
    status: "Shipped",
  },
  {
    id: "S/080124/03",
    commodity: "Textiles",
    destination: "New York",
    type: "Sea",
    grossWeight: "2,000 KG",
    status: "In Transit",
  },
  {
    id: "S/080124/04",
    commodity: "Machinery",
    destination: "Sydney",
    type: "Sea",
    grossWeight: "3,000kg",
    status: "Delivered",
  },
  {
    id: "S/080124/05",
    commodity: "Furniture",
    destination: "Paris",
    type: "Land",
    grossWeight: "1,200 KG",
    status: "In Warehouse",
  },
  {
    id: "S/080124/06",
    commodity: "Automotive parts",
    destination: "Beijing",
    type: "Air",
    grossWeight: "800kg",
    status: "Clearing Customs",
  },
  {
    id: "S/080124/07",
    commodity: "Pharmaceuticals",
    destination: "Mumbai",
    type: "Air",
    grossWeight: "400kg",
    status: "Shipped",
  },
  {
    id: "S/080124/08",
    commodity: "Food products",
    destination: "Dubai",
    type: "Sea",
    grossWeight: "2,500 KG",
    status: "In Transit",
  },
];

export default shipments;
